# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

jil = User.create(name: 'Jil', username: 'jilli26', email: 'jilli26@gmail.com', password: '123')

fiona = Vendor.create(name: 'Fiona', username: 'fiona19', email: 'fiona19@gmail.com')
sam = Vendor.create(name: 'Sam', username: 'sammy23', email: 'sammy23@gmail.com')
chris = Vendor.create(name: 'Chris', username: 'chris123', email: 'chris123@gmail.com')
tom = Vendor.create(name: 'Thomas', username: 'tommy', email: 'tommy@me.com')
leanne = Vendor.create(name: 'Leanne', username: 'leanne', email: 'leanney@me.com')

garden = Venue.create(vendor_id: 1, title: 'Serene Garden', city: 'Hudson Valley', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacus viverra vitae congue eu consequat ac felis. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Eget egestas purus viverra accumsan. Senectus et netus et malesuada. Aenean et tortor at risus viverra. ', photo: 'https://i.imgur.com/M519wy9.jpg', pricing: '$$$', capacity: 100, amenities: '', availability: 'No availability during the spring and summer of 2018', category: 'outdoor', size: 2000, cancellation: 'Half of deposit will be returned if cancellation occurs four or more months prior to wedding.', security_deposit: '15% of the total cost', accessibility: 'Handicap accessible', lat: 41.920902, lng: -73.961289)

rooftop = Venue.create(vendor_id: 2, title: 'Modern Hotel Rooftop', city: 'Midtown Manhattan', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Ipsum a arcu cursus vitae congue. ', photo: 'https://i.imgur.com/lvrwfkR.jpg', pricing: '$$', capacity: 250, amenities: '', availability: '', category: 'hotel', size: 1800, cancellation: 'If canceled six months prior, 40% of deposit will be returned', security_deposit: '', accessibility: 'Handicap accessible', lat: 40.754931, lng: -73.984019)

mansion = Venue.create(vendor_id: 3, title: 'Opulent Mansion', city: 'Long Island', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Magna eget est lorem ipsum dolor sit amet. In fermentum posuere urna nec tincidunt praesent semper feugiat. Velit ut tortor pretium viverra. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Malesuada fames ac turpis egestas integer eget aliquet nibh. Ultrices vitae auctor eu augue. Arcu non odio euismod lacinia at quis risus sed vulputate.', photo: 'https://i.imgur.com/DzMhypq.jpg', pricing: '$$$', capacity: 500, amenities: '', availability: 'As of November 2017, we have availability from November 2018 and beyond', category: 'historic', size: 4000, cancellation: 'Non-refundable depsosit', security_deposit: '10% of the total cost', accessibility: 'Handicap accessible', lat: 40.855931, lng: -73.200669)

clubhouse = Venue.create(vendor_id: 4, title: 'Country Club', city: 'Westchester', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sem integer vitae justo eget magna fermentum. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Arcu bibendum at varius vel pharetra vel turpis nunc. Diam donec adipiscing tristique risus nec. Egestas erat imperdiet sed euismod nisi. Volutpat est velit egestas dui id. Elementum sagittis vitae et leo duis ut. In est ante in nibh mauris.', photo: 'https://i.imgur.com/oJzosF4.jpg', pricing: '$$', capacity: 300, amenities: '', availability: 'Some availability in early to mid 2018; lots of availability the latter half of the year', category: 'clubhouse', size: 3000, cancellation: 'Half deposit returned if canceled 6 months before', security_deposit: '$2000', accessibility: 'Handicap accessible', lat: 41.122019, lng: -73.794852)

ranch = Venue.create(vendor_id: 4, title: 'Expansive, Secluded Ranch', city: 'Carmel', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Auctor urna nunc id cursus metus. Ornare arcu odio ut sem nulla pharetra. Sed egestas egestas fringilla phasellus faucibus. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Urna duis convallis convallis tellus id interdum. At tellus at urna condimentum mattis pellentesque id nibh.', photo: 'https://i.imgur.com/fbQwiCh.jpg', pricing: '$$', capacity: 300, amenities: '', availability: 'Availability starting fall 2018', category: 'outdoor', size: 3000, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 41.430094, lng: -73.680130)

castle = Venue.create(vendor_id: 5, title: 'Castle', city: 'Castle Hill', state: 'NY', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Auctor urna nunc id cursus metus. Ornare arcu odio ut sem nulla pharetra. Sed egestas egestas fringilla phasellus faucibus. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Urna duis convallis convallis tellus id interdum. At tellus at urna condimentum mattis pellentesque id nibh.', photo: 'https://i.imgur.com/s4Y9YX8.jpg', pricing: '$$$', capacity: 350, amenities: '', availability: 'The Castle is open for weddings starting January 2019', category: 'castle', size: 3000, cancellation: '', security_deposit: '8%', accessibility: 'Handicap accessible', lat: 40.817683, lng: -73.850728)

#start here

Venue.create(vendor_id: 6, title: 'Bryant Park Grill', city: 'New York', state: 'NY', description: 'You will find your dream wedding location when you choose the Bryant Park Grill. Surround yourself in the lush garden and gorgeous natural landscape of Bryan Park in New York City. Nothing enhances the beauty of a wedding quite like the jewels of natural surroundings. The venue has been hosting and impressing couples and their guests for many years and is a well-known venue for every size wedding. Designed to resemble an aviary, Bryant Park Grill is a favorite wedding location of many brides and grooms in New York City.', photo: 'https://i.imgur.com/imrb2C0.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Some availability during early summer 2018 and winter 2018-2019', category: 'outdoor', size: 2000, cancellation: '', security_deposit: '10%', accessibility: 'Handicap accessible', lat: 40.753199, lng: -73.982957)

Venue.create(vendor_id: 7, title: 'Plaza Hotel', city: 'New York', state: 'NY', description: "Throughout its history, The Plaza's Grand Ballroom has been the setting for countless lavish weddings and events. Today, the ballroom's neo-Classical decor and new contemporary spirit add life to its initial splendor and its fabled past. We welcome you to become part of the legend.", photo: 'https://i.imgur.com/JbMQZKU.jpg', pricing: '$$$$', capacity: 400, amenities: '', availability: 'The Plaza Hotel invites wedding events starting January 2019', category: 'hotel', size: 4000, cancellation: '', security_deposit: '$500', accessibility: 'Handicap accessible', lat: 40.764469, lng: -73.974488)

Venue.create(vendor_id: 8, title: 'The William Vale Hotel', city: 'Brooklyn', state: 'NY', description: "The William Vale, located in Brooklyn’s Williamsburg neighborhood, rests along the East River’s waterfront. This soaring 22 level hotel features 183 guestrooms and suites, each with their own balcony, and 20,000 square feet of unique event spaces perfect for hosting a range of events. The William Vale’s selection of indoor and outdoor spaces, sweeping views, and unparalleled service is bound to leave a lasting impression for all of your wedding weekend events. Ask about our Winter Wedding Special for preferred rates on food, beverage, room blocks and suites! For any January 1st – March 31st, 2018 wedding inquiries.", photo: 'https://i.imgur.com/O7a1rCK.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Summer through fall 2018 available', category: 'hotel', size: 3000, cancellation: '', security_deposit: '5%', accessibility: 'Handicap accessible', lat: 40.722283, lng: -73.956691)

Venue.create(vendor_id: 9, title: 'Tribeca Rooftop', city: 'New York', state: 'NY', description: "The 15,000-square-foot, 12th-floor penthouse has a 65-foot-long skylight that can light your event with sunlight or the stars. It's filled with elegant crystal chandeliers for extra illumination at night and there's an impressive 1,400-square-foot wood dance floor. You can go straight to the 18,000-square-foot landscaped roof deck from the mezzanine above the dance floor. ", photo: 'https://i.imgur.com/s4Y9YX8.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Select dates in winter 2018 still available', category: 'hotel', size: 1500, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.817683, lng: -73.850728)

Venue.create(vendor_id: 10, title: 'Oheka Castle', city: '', state: 'NY', description: "The Oheka Castle Hotel and Estate serving Long Island and New York, New York, is listed in the National Register of Historic Places. You might feel like you're living in a storybook when you choose the mansion as your wedding venue. The first wedding at the estate took place in 1919 and the staff has been making fanciful events come to life ever since. With only one wedding scheduled each day, to-be-weds receive the full attention of the staff. There are both indoor and outdoor ceremony and reception spaces to choose from, so you won't have any trouble finding just the right place for your celebration.", photo: 'https://i.imgur.com/zDRtFtO.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Oheka is open for weddings beginning in 2019', category: 'castle', size: 3000, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.723443, lng: -74.008349)

Venue.create(vendor_id: 11, title: 'Nomo Soho', city: 'New York', state: 'NY', description: "Designed by Benjamin Noriega Ortiz and inspired by Jean Cocteau's 1946 French film La Belle et la Bête (Beauty and the Beast), the NoMo SoHo (formerly the Mondrian SoHo) in New York City, New York, provides a dreamy wedding experience and luxury hotel accommodations. New York Magazine named NoMo SoHo 'a top Manhattan wedding site' in 2016. Executive Chef N. Salaam offers famous dishes like big eye tuna tartare, Wagyu flatiron steak, truffle flat bread and chamomile panna cotta in the 'Wedding Experience' menu.", photo: 'https://i.imgur.com/JZ3ocXo.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Dates throughout the latter half of 2018 are still open', category: 'hotel', size: 850, cancellation: '', security_deposit: '8%', accessibility: 'Handicap accessible', lat: 40.719883, lng: -74.000157)

Venue.create(vendor_id: 12, title: 'Brooklyn Winery', city: 'New York', state: 'NY', description: "With a fully functioning winery as the backdrop for your nuptials, Brooklyn Winery is uniquely chic—you’ll host your guests in our romantic, sophisticated space filled with reclaimed wood and hand-selected vintage adornments while sipping wine made on premises. Your dedicated event manager will carefully assist with all of the details, from helping you select your individual wedding menu to making sure every element is perfect when it’s time to walk down the aisle.", photo: 'https://i.imgur.com/PugaJGC.jpg', pricing: '$$$', capacity: 150, amenities: '', availability: 'We are currently booking weddings for dates beginning November 2017 and beyond', category: 'winery', size: 780, cancellation: '', security_deposit: '7%', accessibility: 'Handicap accessible', lat: 40.717272, lng: -73.955107)
