# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or create!d alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)

jil = User.create!(name: 'Jil', username: 'jilli26', email: 'jilli26@gmail.com', password: '123')

fiona = Vendor.create!(name: 'Fiona', username: 'fiona19', email: 'fiona19@gmail.com')
sam = Vendor.create!(name: 'Sam', username: 'sammy23', email: 'sammy23@gmail.com')
chris = Vendor.create!(name: 'Chris', username: 'chris123', email: 'chris123@gmail.com')
tom = Vendor.create!(name: 'Thomas', username: 'tommy', email: 'tommy@me.com')
leanne = Vendor.create!(name: 'Leanne', username: 'leanne', email: 'leanney@me.com')

garden = Venue.create!(vendor_id: 1, title: 'Valley Garden', city: 'Hudson Valley', state: 'NY', description: "Intimate, romantic, located in the heart of the Hudson Valley, this early 1800's Greek Revival Manor has been impeccably restored to its original grace and grandeur. Introduce your guests to the casual elegance of a country estate with the sophistication & quality of Manhattan. Features: One wedding a day—you decide the start time, luxurious gardens with a pond, waterfalls & fountains, outdoor garden wedding ceremony area along with indoor area in case of inclement weather, we are all-inclusive—no site fees, comfortably accommodates 200 guests, huge dance floor, less than one hour from Manhattan & NJ.", photo: 'https://i.imgur.com/05CXdxX.jpg', pricing: '$$$', capacity: 100, amenities: '', availability: 'No availability during the spring and summer of 2018', category: 'outdoor', size: 2000, cancellation: 'Half of deposit will be returned if cancellation occurs four or more months prior to wedding.', security_deposit: '15% of the total cost', accessibility: 'Handicap accessible', lat: 41.920902, lng: -73.961289, phone: '212-342-5135', address: '121 Fort Rd', ratings: 132)

rooftop = Venue.create!(vendor_id: 1, title: 'Midtown Loft & Terrace', city: 'Manhattan', state: 'NY', description: 'Midtown Loft (5,000 square ft), our premier indoor event space, accommodates up to 300 people for cocktails and comfortably seats 180 for formal dinners. Midtown Loft is both striking and functional with high ceilings, marble bathrooms, central air, adjustable spot lighting, and a fully equipped kitchen. The space provides an upbeat style and sophistication with its location on the world’s most famous avenue. Large windows on all four sides offer stunning views of the skyline while letting in natural light to complement the warmth of the polished oak flooring. We are prepared to accommodate any event—from weddings and private celebrations to product launches, fashion shows, fundraisers and trade shows. Various setup options are available, from small intimate receptions to large parties.', photo: 'https://i.imgur.com/lvrwfkR.jpg', pricing: '$$', capacity: 250, amenities: '', availability: '', category: 'hotel', size: 1800, cancellation: 'If canceled six months prior, 40% of deposit will be returned', security_deposit: '', accessibility: 'Handicap accessible', lat: 40.754931, lng: -73.984019, phone: '212-343-1222', address: '267 5th Ave, New York, NY, 10016', ratings: 132)

mansion = Venue.create!(vendor_id: 1, title: 'The Mansion at Oyster Bay stands majestically in the heart of 120 perfectly manicured acres in Woodbury, Long Island. The ambiance of this former magnificent Gold Coast estate is rich with elegance and hospitality, but updated with modern amenities. Come enjoy this experience of Long Island Gold Coast luxury, and share it with your guests in an unforgettable setting.', photo: 'https://i.imgur.com/DzMhypq.jpg', pricing: '$$$', capacity: 500, amenities: '', availability: 'As of November 2017, we have availability from November 2018 and beyond', category: 'historic', size: 4000, cancellation: 'Non-refundable depsosit', security_deposit: '10% of the total cost', accessibility: 'Handicap accessible', lat: 40.855931, lng: -73.200669, phone: '(516) 921-5707', address: '1 S Woods Rd, Woodbury, NY 11797', ratings: 56)

countryclub = Venue.create!(vendor_id: 2, title: 'Westchester Country Club', city: 'Westchester', state: 'NY', description: 'Henry Hill Farm offers a wonderful country atmosphere with streams, ponds, and ravines all on site. With a unique and historic wooden framed barn, 75 acres of rolling hills, and endless acres of nature, your wedding will surely be as picturesque as it gets. Say your “I do’s” under the gorgeous sunset surrounded by all your family and friends. Helping you create! the most wonderful memories is what Henry Hill Farm sets out to do, so you can sit back and just relax on your big day. Perfect for couples who appreciate the beauty in nature, this venue will be the special touch that your wedding needs!', photo: 'https://i.imgur.com/rFkg8Z7.jpg', pricing: '$$', capacity: 300, amenities: '', availability: 'Some availability in early to mid 2018; lots of availability the latter half of the year', category: 'clubhouse', size: 3000, cancellation: 'Half deposit returned if canceled 6 months before', security_deposit: '$2000', accessibility: 'Handicap accessible', lat: 41.122019, lng: -73.794852, phone: '212-044-1267', address: '2 Bluestone Rd, White Plains, NY, 11790', ratings: 40)

ranch = Venue.create!(vendor_id: 2, title: 'Spencer Hill Ranch', city: 'Carmel', state: 'NY', description: 'Spencer Hill Ranch is an expansive, secluded ranch in the countryside with nature including streams, ponds, and ravines surrounding lush greenery. Couples can wed beneath our wooden framed barn with a stunning backdrop of 50 acres of hills.', photo: 'https://i.imgur.com/fbQwiCh.jpg', pricing: '$$', capacity: 300, amenities: '', availability: 'Availability starting fall 2018', category: 'outdoor', size: 3000, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 41.430094, lng: -73.680130, phone: '845-398-1722', address: '20 Crosby Rd, Carmel, NY, 10600', ratings: 22)

castle = Venue.create!(vendor_id: 2, title: 'Lyndhurst Castle', city: 'Tarrytown', state: 'NY', description: 'Seated on sixty-seven acres overlooking the gorgeous Hudson River, Lyndhurst is an unforgettable venue for weddings, receptions, dinner parties, and celebrations only thirty-five minutes from New York City. Ceremonies can be held on Lyndhurst’s sweeping great lawn with the picturesque backdrop of the fairy-tale mansion and river views. Ceremonies may also be held in the fragrant Rose Garden with its pergola draped in roses. The Carriage House features a semi-permanent tent which hosts up to 300 guests for receptions, dinner, and dancing.', photo: 'https://i.imgur.com/8MO0vVM.jpg', pricing: '$$$', capacity: 350, amenities: '', availability: 'The Castle is open for weddings starting January 2019', category: 'castle', size: 3000, cancellation: '', security_deposit: '8%', accessibility: 'Handicap accessible', lat: 40.817683, lng: -73.850728, phone: '340-258-1589', address: '635 S Broadway, Tarrytown, NY 10591', ratings: 94)

#start here

bryant_park = Venue.create!(vendor_id: 1, title: 'Bryant Park Grill', city: 'New York', state: 'NY', description: 'You will find your dream wedding location when you choose the Bryant Park Grill. Surround yourself in the lush garden and gorgeous natural landscape of Bryan Park in New York City. Nothing enhances the beauty of a wedding quite like the jewels of natural surroundings. The venue has been hosting and impressing couples and their guests for many years and is a well-known venue for every size wedding. Designed to resemble an aviary, Bryant Park Grill is a favorite wedding location of many brides and grooms in New York City.', photo: 'https://i.imgur.com/imrb2C0.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Some availability during early summer 2018 and winter 2018-2019', category: 'outdoor', size: 2000, cancellation: '', security_deposit: '10%', accessibility: 'Handicap accessible', lat: 40.753199, lng: -73.982957, phone: '(212) 840-6500', address: '25 W 40th St, New York, NY 10018', ratings: 234)

plaza = Venue.create!(vendor_id: 4, title: 'Plaza Hotel', city: 'New York', state: 'NY', description: "Throughout its history, The Plaza's Grand Ballroom has been the setting for countless lavish weddings and events. Today, the ballroom's neo-Classical decor and new contemporary spirit add life to its initial splendor and its fabled past. We welcome you to become part of the legend.", photo: 'https://i.imgur.com/JbMQZKU.jpg', pricing: '$$$$', capacity: 400, amenities: '', availability: 'The Plaza Hotel invites wedding events starting January 2019', category: 'hotel', size: 4000, cancellation: '', security_deposit: '$500', accessibility: 'Handicap accessible', lat: 40.764469, lng: -73.974488, phone: '(212) 840-6500', address: '768 5th Ave, New York, NY 10019', ratings: 318)

william_vale = Venue.create!(vendor_id: 3, title: 'The William Vale Hotel', city: 'Brooklyn', state: 'NY', description: "The William Vale, located in Brooklyn’s Williamsburg neighborhood, rests along the East River’s waterfront. This soaring 22 level hotel features 183 guestrooms and suites, each with their own balcony, and 20,000 square feet of unique event spaces perfect for hosting a range of events. The William Vale’s selection of indoor and outdoor spaces, sweeping views, and unparalleled service is bound to leave a lasting impression for all of your wedding weekend events. Ask about our Winter Wedding Special for preferred rates on food, beverage, room blocks and suites! For any January 1st – March 31st, 2018 wedding inquiries.", photo: 'https://i.imgur.com/O7a1rCK.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Summer through fall 2018 available', category: 'hotel', size: 3000, cancellation: '', security_deposit: '5%', accessibility: 'Handicap accessible', lat: 40.722283, lng: -73.956691, phone: '(718) 631-8400', address: '111 N 12th St, Brooklyn, NY 11249', ratings: 98)

tribeca_rooftop = Venue.create!(vendor_id: 3, title: 'Tribeca Rooftop', city: 'New York', state: 'NY', description: "The 15,000-square-foot, 12th-floor penthouse has a 65-foot-long skylight that can light your event with sunlight or the stars. It's filled with elegant crystal chandeliers for extra illumination at night and there's an impressive 1,400-square-foot wood dance floor. You can go straight to the 18,000-square-foot landscaped roof deck from the mezzanine above the dance floor. ", photo: 'https://i.imgur.com/s4Y9YX8.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Select dates in winter 2018 still available', category: 'hotel', size: 1500, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.817683, lng: -73.850728, phone: '(718) 631-8400', address: '111 N 12th St, Brooklyn, NY 11249', ratings: 98)

oheka_castle = Venue.create!(vendor_id: 1, title: 'Oheka Castle', city: 'Long Island', state: 'NY', description: "The Oheka Castle Hotel and Estate serving Long Island and New York, New York, is listed in the National Register of Historic Places. You might feel like you're living in a storybook when you choose the mansion as your wedding venue. The first wedding at the estate took place in 1919 and the staff has been making fanciful events come to life ever since. With only one wedding scheduled each day, to-be-weds receive the full attention of the staff. There are both indoor and outdoor ceremony and reception spaces to choose from, so you won't have any trouble finding just the right place for your celebration.", photo: 'https://i.imgur.com/zDRtFtO.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Oheka is open for weddings beginning in 2019', category: 'castle', size: 3000, cancellation: '', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.723443, lng: -74.008349, phone: '(212) 625-2600', address: '2 Desbrosses St, New York, NY 10013', ratings: 308)

nomo_soho = Venue.create!(vendor_id: 1, title: 'Nomo Soho', city: 'New York', state: 'NY', description: "Designed by Benjamin Noriega Ortiz and inspired by Jean Cocteau's 1946 French film La Belle et la Bête (Beauty and the Beast), the NoMo SoHo (formerly the Mondrian SoHo) in New York City, New York, provides a dreamy wedding experience and luxury hotel accommodations. New York Magazine named NoMo SoHo 'a top Manhattan wedding site' in 2016. Executive Chef N. Salaam offers famous dishes like big eye tuna tartare, Wagyu flatiron steak, truffle flat bread and chamomile panna cotta in the 'Wedding Experience' menu.", photo: 'https://i.imgur.com/JZ3ocXo.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: 'Dates throughout the latter half of 2018 are still open', category: 'hotel', size: 850, cancellation: '', security_deposit: '8%', accessibility: 'Handicap accessible', lat: 40.719883, lng: -74.000157, phone: '(646) 218-6400', address: '29 Crosby St, New York, NY 10013', ratings: 401)

bk_winery = Venue.create!(vendor_id: 2, title: 'Brooklyn Winery', city: 'Brooklyn', state: 'NY', description: "With a fully functioning winery as the backdrop for your nuptials, Brooklyn Winery is uniquely chic—you’ll host your guests in our romantic, sophisticated space filled with reclaimed wood and hand-selected vintage adornments while sipping wine made on premises. Your dedicated event manager will carefully assist with all of the details, from helping you select your individual wedding menu to making sure every element is perfect when it’s time to walk down the aisle.", photo: 'https://i.imgur.com/PugaJGC.jpg', pricing: '$$$', capacity: 150, amenities: '', availability: 'We are currently booking weddings for dates beginning November 2017 and beyond', category: 'winery', size: 780, cancellation: '', security_deposit: '7%', accessibility: 'Handicap accessible', lat: 40.717272, lng: -73.955107, phone: '(347) 763-1506', address: '213 N 8th St, Brooklyn, NY 11211', ratings: 267)

decoy = Venue.create!(vendor_id: 3, title: 'Decoy', city: 'New York', state: 'NY', description: "From the team that bought you RedFarm, Chef Joe Ng and Managing Partner Ed Schoenfeld introduce an inspired take on the traditional Peking Duck. Crispy-skinned Peking Ducks are served with paper-thin pancakes, and accompanied by appetizers such as cold sweet potato noodles topped with uni and octopus sashimi salad served in a teapot overflowing with clouds. Rated by the New York Post as one of the 'sexiest restaurants in NYC', Brooklyn-based Crème Design create!d an intimate space featuring dark reclaimed wood and black marble.", photo: 'https://i.imgur.com/PugaJGC.jpg', pricing: '$$', capacity: 40, amenities: '', availability: 'Currently available for weddings for dates beginning November 2017 and beyond', category: 'restaurant', size: 350, cancellation: '3 months cancellation required', security_deposit: '5%', accessibility: 'Handicap accessible', lat: 40.734194, lng: -74.006494, phone: '(212) 691-9700', address: '529-1/2 Hudson St, New York, NY 10014', ratings: 54)

buddakan = Venue.create!(vendor_id: 4, title: 'Buddakan', city: 'New York', state: 'NY', description: "The surreal atmosphere of this awe-inspiring restaurant in New York’s Meatpacking district combines the serenity of Asia with the flamboyance of 16th century Paris. The menu features fanciful interpretations of Chinese dishes and delights even the most discriminating palates.", photo: 'https://i.imgur.com/0iPeWJU.jpg', pricing: '$$$$', capacity: 40, amenities: '', availability: 'Currently available for weddings for dates beginning November 2017 and beyond', category: 'restaurant', size: 5000, cancellation: '6 months cancellation required for full refund', security_deposit: '10%', accessibility: 'Handicap accessible', lat: 40.742279, lng: -74.004819, phone: '(212) 989-6699', address: '75 9th Ave, New York, NY 10011', ratings: 349)

unix = Venue.create!(vendor_id: 4, title: 'Unix Gallery', city: 'New York', state: 'NY', description: "Art gallery located in the heart of downtown Manhattan, in the central and iconic Flatiron district. Our space is bright, airy, and can accommodate events of all types.", photo: 'https://i.imgur.com/uxVpJtB.jpg', pricing: '$$', capacity: 180, amenities: '', availability: 'Currently available for weddings for dates beginning November 2017 and beyond', category: 'restaurant', size: 2000, cancellation: '6 months cancellation required for full refund', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.748957, lng: -74.005425, phone: '(212) 209-1572', address: '532 W 24th St, New York, NY 10001', ratings: 72)

housing_works = Venue.create!(vendor_id: 4, title: "Housing Works Bookstore Soho", city: "New York", state: 'NY', description: "With a setting that's undeniably enticing for altruistic couples, the Housing Works Bookstore in SoHo & The Works Catering is a quintessentially New York venue. After starting out as a healing charity for those affected by HIV/AIDS and homelessness, the venue has expanded to continue its work while acting as a wedding ceremony and reception venue. Whether happy couples prefer a laid-back vibe or black tie, traditional or non-traditional, this venue fits the bill. As far as historic wedding venues go, the Housing Works Bookstore in SoHo & the Works Catering is hard to beat. With a backdrop of books for the ceremony and reception, it's also ideal for those planning a literature themed wedding. A combination of 20-foot ceilings and mahogany bookcases gives this venue an antique charm.", photo: 'https://i.imgur.com/Uv9WJsr.jpg', pricing: '$$', capacity: 250, amenities: '', availability: "Currently available for weddings for dates beginning Dec 2017", category: 'bookstore', size: 1800, cancellation: '6 months cancellation required for full refund', security_deposit: '$1000', accessibility: 'Handicap accessible', lat: 40.724569, lng: -73.996485, phone: '(212) 334-3324', address: '126 Crosby St, New York, NY 10012', ratings: 464)

museum = Venue.create!(vendor_id: 4, title: "American Museum of Natural History", city: "New York", state: 'NY', description: "Have your quintessential wedding day in a uniquely New York location. From the most opulent surroundings to the more modern designs of the 21st century, each hall’s singular characteristics ensure your milestones become lasting impressions.", photo: 'https://i.imgur.com/yDv0oU9.jpg', pricing: '$$$$', capacity: 550, amenities: '', availability: "Booking dates in mid 2018", category: 'museum', size: 5000, cancellation: '6 months cancellation required for half refund', security_deposit: '15%', accessibility: 'Handicap accessible', lat: 40.781324, lng: -73.973988, phone: '(212) 769-5100', address: '1Central Park West & 79th St, New York, NY 10024', ratings: 194)

frick = Venue.create!(vendor_id: 4, title: "Frick Collection", city: "New York", state: 'NY', description: "The Frick Collection evokes the glamour of Gilded Age New York and provides a uniquely elegant setting for any reception, cocktail party, or dinner. In various configurations, the Frick can accommodate up to 500 people for a cocktail reception and 180 for a seated dinner. All events happen after hours from 7:00 p.m. to midnight, giving guests the opportunity to experience the Frick’s preeminent art collection in an unhurried way, as Mr. Frick might have.", photo: 'https://i.imgur.com/lopfona.jpg', pricing: '$$$$', capacity: 310, amenities: '', availability: "Booking dates in mid 2018", category: 'art gallery', size: 1900, cancellation: '8 months cancellation required for half refund', security_deposit: '15%', accessibility: 'Handicap accessible', lat: 40.770970, lng: -73.967384, phone: '212-991-5774', address: '1 East 70th Street, New York, NY 10021', ratings: 198)

white_rabbit = Venue.create!(vendor_id: 5, title: "White Rabbit", city: "Singapore", state: 'Singapore', description: "A genre-defining restaurant and bar housed in a beautifully-restored 1940s chapel, spread over 40,000 square feet of grounds. The White Rabbit serves a fresh take on both classic European comfort food and cocktails, aiming to deliver an impeccable dining experience without the stuffiness of a typical fine dining establishment. It is a place where time stands still and one feels naturally at ease; be it for a casual meal or a celebration of epic proportions. Whether it is to celebrate the arrival of a little one, the union of a couple or a means of thanking your key clients and colleagues, The White Rabbit makes for a one-of-a-kind venue, fully customisable to your individual needs.", photo: 'https://i.imgur.com/vSEzL21.jpg', pricing: '$$$', capacity: 250, amenities: '', availability: "Booking dates in mid 2018", category: 'restaurant', size: 2000, cancellation: '6 months cancellation required for half refund', security_deposit: '7%', accessibility: 'Handicap accessible', lat: 40.717272, lng: -73.955107, phone: '+65 6473 9965', address: '39C Harding Rd, Singapore 249541', ratings: 198)

altitude = Venue.create!(vendor_id: 5, title: "1-Altitude", city: "Singapore", state: 'Singapore', description: "1-Altitude is Singapore’s top wedding venue offering the finest personalized service to fulfill your dream wedding. Exchange your vows during sunset at Singapore’s highest wedding solemnization venue at the rooftop 1-Altitude Bar & Gallery, create! lasting memories over an elegant wedding dinner at our award-winning restaurant Stellar on Level 62 and head over to the ultimate VIP club Altimate on Level 61 for your wedding after party. With the awe-inspiring 360 degree views, come take a peek into our world of lavish weddings at 1-Altitude Bar & Gallery and Stellar. Our wedding menus and packages are specially designed to your requirements. Enjoy the full 1-Altitude wedding experience. Get in touch with us now!", photo: 'https://i.imgur.com/3j3fXwa.jpg', pricing: '$$$$', capacity: 250, amenities: '', availability: "Booking dates available in mid 2019", category: 'hotel', size: 2000, cancellation: '6 months cancellation required for half refund', security_deposit: '7%', accessibility: 'Handicap accessible', lat: 1.304829, lng: 103.813515, phone: '+65 6438 0410', address: '1 Raffles Place, Singapore 048616', ratings: 213)

lantern = Venue.create!(vendor_id: 5, title: "Lantern Rooftop Bar", city: "Singapore", state: 'Singapore', description: "Recognised as one of the best hotel bars in the world, Lantern provides a superlative backdrop for unforgettable weddings and glamorous events with enthralling views of the city skyline. Located at the rooftop of The Fullerton Bay Hotel Singapore (level 7), guests will be able to enjoy a bird's eye view of the city's landmarks while indulging in specialty cocktails and gourmet tapas.", photo: 'https://i.imgur.com/GbD4opR.jpg', pricing: '$$$', capacity: 180, amenities: '', availability: "Currently accepting reservations for weddings starting early 2019", category: 'hotel', size: 2000, cancellation: '6 months cancellation required for half refund', security_deposit: '7%', accessibility: 'Handicap accessible', lat: 1.283187, lng: 103.853852, phone: '+65 6597 5299', address: '80 Collyer Quay, Singapore 049326', ratings: 213)
